name: Windows x64 Build & Release
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
env:
  BUILD_TYPE: Release
 
jobs:
  build:
    name: MSVC x64
    runs-on: windows-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v7
 
      - name: Configure
        run: cmake -B build -A x64 -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
 
      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
 
      - name: Collect
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force staging | Out-Null
          cmake --install build --config ${{ env.BUILD_TYPE }} --prefix staging
          if ($LASTEXITCODE -ne 0 -or -not (Test-Path 'staging/*')) {
            Get-ChildItem -Path "build/bin/${{ env.BUILD_TYPE }}" -Filter "*.dll" -Recurse | ForEach-Object {
                $relativePath = $_.FullName.Substring((Get-Item "build/bin/${{ env.BUILD_TYPE }}").FullName.Length + 1)
                $targetPath = Join-Path "staging" (Split-Path $relativePath)
                if (-not (Test-Path $targetPath)) { New-Item -ItemType Directory -Path $targetPath -Force > $null }
                Copy-Item $_.FullName -Destination $targetPath -Force
            }
          }
 
      - name: Package
        shell: pwsh
        run: |
          $name = ('${{ github.event.repository.name }}-${{ github.ref_name }}-windows-x64').Replace('/','-')
          Compress-Archive -Path staging/* -DestinationPath "$name.zip"
          Add-Content $env:GITHUB_ENV "PACKAGE=$name.zip"
 
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-windows-x64
          path: ${{ env.PACKAGE }}
          archive: false
          if-no-files-found: error
